version: '3'
services:

  # Go Server
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: vgs-server
    ports:
      - 12345:12345
    tty: true # コンテナの起動永続化
    volumes:
      - ./server:/go/src/github.com/akitomonam/paper-management-app/server
      - .git:/go/src/github.com/akitomonam/paper-management-app/.git
    depends_on:
      - 'db'
  # client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vgs-client
    ports:
      - 8080:8080
    tty: true # コンテナの起動永続化
    volumes:
      - ./client:/usr/src/app/client
      - .git:/usr/src/app/.git
  # DB
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: vgs-db
    ports:
      - 3306:3306
    environment:
      # - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      # - MYSQL_PASSWORD=${DB_PASS}
      # - MYSQL_USER=${DB_USER}
      # - TZ=${TZ}
    volumes:
      - ./db/mysql-store:/var/lib/mysql  # データ永続化
      - ./db/mysql-logs:/var/log/mysql